port = "1443" # Cloaka http port
mode = "DEV" # Run mode (DEV for development. PROD for production)
datapack = "" # Your datapack path
template =  "" # Your template path
static = "/public/" # Path to your static assets folder

[https]
enabled = false
cert = ""
key = ""

[cache]
enabled = true
type = "memory"

[[routes]]
path = "/community/activity"
method = "GET"
file = "activity.lua"

[paypal]
currency = "EUR"
mode = "sandbox" # Paypal mode (sandbox for testing. live for production)
public = "" # Your public_key
secret = "" # Your private_key
promo = 10
description = "Cloaka donation"

[paypal.payment]
points = 5
min = 10
max = 100

[captcha]
public = "" # Google reCAPTCHA public_key
secret = "" # secret_key

[register]
experience = 4200
health = 42
healthMax = 42
level = 8
mana = 0
manaMax = 0
premdays = 100
stamina = 4200

[register.female]
lookaddons = 10
lookbody = 10
lookfeet = 10
lookhead = 10
looktype = 10

[register.male]
lookaddons = 10
lookbody = 10
lookfeet = 10
lookhead = 10
looktype = 10

[register.skills]
axe = 10
club = 10
dist = 10
fish = 10
fist = 10
shield = 10
sword = 10




